# Generated by Django 3.0.6 on 2020-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0012_auto_20200718_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordersupdate',
            name='update_desc',
            field=models.CharField(default='Checking Order Details', max_length=5000),
        ),
    ]
